FROM python
RUN pip install pip install --upgrade pip

COPY ./requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

COPY ./src/symbols.py /symbols.py
COPY ./src/queue-eod.py /queue-eod.py
COPY ./src/EOD.py /EOD.py

CMD  python queue-eod.py
