apiVersion: batch/v1
kind: CronJob
metadata:
  name: forecast-eod
spec:
  # UTC
  schedule: "20 4 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          name: forecast-eod
        spec:
          containers:
          - name: forecast-eod
            image: gregckrause/forecast-eod:latest
            env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: RootUser
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo
                  key: RootPassword
            - name: QUANDL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: quandl
                  key: APIKey
          restartPolicy: OnFailure
      parallelism: 1
