apiVersion: batch/v1
kind: Job
metadata:
  name: queue-forecast-eod
spec:
  parallelism: 1
  template:
    metadata:
      name: queue-forecast-eod
    spec:
      containers:
      - name: queue-eod
        image: gregckrause/queue-eod:latest
        env:
        - name: QUEUE
          value: "forecasteod"
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo
              key: RootUser
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo
              key: RootPassword
        - name: QUANDL_API_KEY
          valueFrom:
            secretKeyRef:
              name: quandl
              key: APIKey
      restartPolicy: OnFailure
